version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      rebase-strategy: "auto"
      open-pull-requests-limit: 3
      groups:
          minor-and-patch:
               update-types:
                   - "minor"
                   - "patch"

    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
      groups:
          # Production dependencies without breaking changes
          dependencies:
              dependency-type: "production"
              update-types:
                  - "minor"
                  - "patch"
          # Production dependencies with breaking changes
          dependencies-major:
              dependency-type: "production"
              update-types:
                  - "major"
          # Development dependencies
          dev-dependencies:
              dependency-type: "development"
