name: Checks

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v5

            - uses: actions/setup-node@v6
              with:
                  node-version-file: ".nvmrc"
                  registry-url: https://npm.pkg.github.com/
                  scope: "@weglot"

            - run: npm install

            - run: npm run build

            - name: Check if the compilation is up to date
              run: git add -N . && git diff --no-patch --exit-code

            - run: npm test

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  tools: composer:v2
                  ini-file: development

            - run: composer install

            - run: composer phpstan
